name: Repository Automation
on:
  pull_request:
    types:
      - closed

env:
  MY_VARIABLE: ${{ secrets.API_TOKEN }}  # Pass the secret as an environment variable

jobs:
  create_artifactory:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install the requests module

      - name: Check Python version
        run: python --version

      - name: Execute Repository Automation Script
        run: python execute_script.py
